export const LEGACY_FORM_UI = {
  title: 'Field Activity Submission',
  steps: [
    { id: 1, title: 'Activity Details' },
    { id: 2, title: 'Participation' },
    { id: 3, title: 'Issues & Evidence' },
    { id: 4, title: 'Review & Submit' },
  ],
  activityTypes: ['Training', 'Awareness Program', 'Food Distribution', 'Health Camp', 'Survey', 'Meeting'],
  regions: ['North Region', 'South Region', 'East Region', 'West Region', 'Central Region'],
  beneficiaryCategories: ['Farmers', 'Students', 'Women', 'Children', 'Senior Citizens', 'General Public'],
  issueOptions: [
    'Water Shortage',
    'Low Attendance',
    'Rain / Weather',
    'Resource Shortage',
    'Transport Issues',
    'Technical Issues',
  ],
  labels: {
    activityType: 'Activity Type',
    activityTitle: 'Activity Title',
    activityDate: 'Activity Date',
    region: 'Region / Village',
    locationDetails: 'Location Details (optional)',
    totalParticipants: 'Total Participants',
    maleCount: 'Male',
    femaleCount: 'Female',
    childrenCount: 'Children (optional)',
    beneficiaryCategory: 'Beneficiary Category',
    issuesTags: 'Issues Observed (optional)',
    additionalNotes: 'Additional Notes (optional)',
    evidenceImages: 'Evidence Images (optional)',
    participantBreakdown: 'Participant Breakdown',
  },
  placeholders: {
    activityType: 'Select an activity type',
    activityTitle: 'e.g., Health Camp - Village X',
    region: 'Select a region',
    locationDetails: 'Specific village, landmark, or address',
    totalParticipants: '0',
    maleCount: '0',
    femaleCount: '0',
    childrenCount: '0',
    additionalNotes: 'Any other observations...',
  },
  helpers: {
    issuesHint: 'Select all issues that apply',
    imagesHint: 'Upload up to 10 images (JPEG, PNG, WebP, GIF — max 5MB each)',
    reviewHint: 'Please review your responses before submitting.',
  },
};

export const getLegacyEnglishOptions = (ui) => ({
  activityTypes: ui?.englishValues?.activityTypes || LEGACY_FORM_UI.activityTypes,
  regions: ui?.englishValues?.regions || LEGACY_FORM_UI.regions,
  beneficiaryCategories: ui?.englishValues?.beneficiaryCategories || LEGACY_FORM_UI.beneficiaryCategories,
  issueOptions: ui?.englishValues?.issueOptions || LEGACY_FORM_UI.issueOptions,
});
